services:
  # Backend Service
  - type: web
    name: inventory-backend
    env: node
    buildCommand: npm install
    rootDir: backend
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://stevenpenero21:tosh123@cluster0.d7pjzci.mongodb.net/
      - key: JWT_SECRET
        value: change_me_development_secret
      - key: JWT_EXPIRES
        value: 1h

  # Frontend Service
  - type: web
    name: inventory-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: inventory-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'