services:
  # Backend Service
  - type: web
    name: inventory-backend
    env: node
    buildCommand: npm install
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://stevenpenero21:tosh123@cluster0.d7pjzci.mongodb.net/
      - key: JWT_SECRET
        value: change_me_development_secret
      - key: JWT_EXPIRES
        value: 1h
    plan: free

  # Frontend Service
  - type: static
    name: inventory-frontend
    buildCommand: npm install && npm run build
    publish: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: inventory-backend
          property: url
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    plan: free